### ISSUE TITLE
why not call zmq_recv in uv_poll callback?

### ISSUE THREAD

**Issue by aggronmagi** [pijyoi/zmq_libev#1]
uv_poll_t — Poll handle
Poll handles are used to watch file descriptors for readability, writability and disconnection similar to the purpose of poll(2).

in function uv_zsock_init:
uv_poll_init_socket(loop, &wz->w_poll, sockfd);
use poll to watch the socket readability.

why not call zmq_recv from function below?
void s_poll_cb(uv_poll_t *handle, int status, int events)

**Comment by pijyoi** [comment]
Zeromq FDs are edge-triggered. Thus a Zsock can  continue to be readable after the FD stops being readable.

The Poll callback is empty as all handling that needs to be done is in the Check callback.

**Comment by aggronmagi** [comment]
thank you!
