### ISSUE TITLE
check_cb question

### ISSUE THREAD

**Issue by chaoshendasixiong** [pijyoi/zmq_libev#2]
why check_cb process the zmq msg instead of io_cb？

**Comment by pijyoi** [comment]
Zmq fd is edge triggered. Io_cb is fired only when the zmq socket transitions from unreadable to readable.

**Comment by chaoshendasixiong** [comment]
can't we processe multiple message in one notification which ZMQ_POLLIN?

**Comment by pijyoi** [comment]
Processing only one message per event loop iteration ensures that other
loop events also get their turn to execute.
